export const URLS = {
  home:           '/#/',
  login:          '/#/login',
  register:       '/#/register',
  search:         '/#/search',
  basket:         '/#/basket',
  contact:        '/#/contact',
  about:          '/#/about',
  scoreBoard:     '/#/score-board',
  administration: '/#/administration',
  profile:        '/#/profile',
  changePassword: '/#/privacy-security/change-password',
  forgotPassword: '/#/forgot-password',
  addressSelect:  '/#/address/select',
  addressCreate:  '/#/address/create',
  deliveryMethod: '/#/delivery-method',
  payment:        '/#/payment/shop',
  orderSummary:   '/#/order-summary',
  orderCompletion:'/#/order-completion',
  recycle:        '/#/recycle',
  complaint:      '/#/complain',
  photoWall:      '/#/photo-wall',
  deluxe:         '/#/deluxe-membership',
};
